### ISSUE TITLE
Feedback: top, services

### ISSUE THREAD

**Issue by VienArchway** [VienArchway/migrations-homepage#8]

**Comment by hieuluong** [comment]
- Header:
    - [ ]: nút  お問い合わせ nên resize nhỏ lại

- Bottom:
    - [ ]: down chữ `what's your challenge for us? sales@archway.co.jp` nên để bên phải logo luôn, để phần hạn chế bớt chiều cao phần bottom

- Top page:
    - [ ] : Font chữ nhạt bớt

- Services.atlassian:
    - [ ] : Font chữ nhạt bớt
    - [ ] : Background vàng nên đổi màu nhạt bớt
    - [ ] : Nên thêm icon vô những services trong phần 製品 gần giống top menu của trang https://www.atlassian.com/

**Comment by ngochaarchway** [comment]
1. Top - Home pages
- Should choose the main color for all pages.
- Background color with light color of the main color
- Text with font size different but using the main color instead of black. It makes "hard" feeling.
- The same contact buttons on the closed position. Should one of them to other layout or link,... Redesign contact button: hiện tại nhìn hơi to, cứng, nên làm hẹp lại 1 tí, cho nó hình mượt mà hơn
- Icon color should not be all in black
- Contact section color should be using a lighter color
- Complete menu with implement contents
- what's your challenge for us?
 sales@archway.co.jp
-> W, email should be a link to send email or contact
- Items of the menu on the bottom should be arranged as the menu on the top. 
- Company information is Archway, not Archway Factory
- Menu:
 + Order of services in the menu, atlasian does not in menu service


2. Services
- Microservice
 + Explain content should be compared with ppt file: 
 + Should review the layout of highlight content because it the same content with above but highlights. 
 + Missed content in p5 of ppt
- DevOps:
 + Content not enough
   * 新しい開発スタイルの適用によるビジネス価値提供サイクルの劇的な短縮を実現します。
   * DevOps 導入: List does not show all mean
- Atlassian
 + Main color
 + Highlight section color
-

**Comment by VienArchway** [comment]
> * Header:
>   
>   * [ x]  : nút  お問い合わせ nên resize nhỏ lại
>   * [ ]  : nội dung của header khi ở màn hình lớn và trong sidebar của mobile khác nhau
>> Mobile chữ nên to hơn!

> * Bottom:
>   
>   * [ ]  : chữ `what's your challenge for us? sales@archway.co.jp` nên để bên phải logo luôn, để phần hạn chế bớt chiều cao
>> keep design. dàn ngang sẽ kì 
> * Top page:
>   
>   * [ x]  : Font chữ nhạt bớt
> * Services.atlassian:
>   
>   * [ x]  : Font chữ nhạt bớt
>   * [x ]  : Background vàng nên đổi màu nhạt bớt
>   * [x ]  : Nên thêm icon vô những services trong phần 製品 gần giống top menu của trang https://www.atlassian.com/, https://www.atlassian.com/software

**Comment by VienArchway** [comment]
> 1. Top - Home pages
> 
> * Should choose the main color for all pages.
>> keeping review and propose color palette!
> * Background color with light color of the main color
>> should be light color (white color is better). 
> * Text with font size different but using the main color instead of black. It makes "hard" feeling.
>> no change. adjust color to more gray.
> * ~~The same contact buttons on the closed position. Should one of them to other layout or link,... Redesign contact button: hiện tại nhìn hơi to, cứng, nên làm hẹp lại 1 tí, cho nó hình mượt mà hơn~~
> fixed
> * Icon color should not be all in black
>> no change
> * Contact section color should be using a lighter color
>> no change. Prefer color palette.
> * ~~Complete menu with implement contents~~
>> fixed
> * what's your challenge for us?
>   [sales@archway.co.jp](mailto:sales@archway.co.jp)
>   -> W, email should be a link to send email or contact
>> keep in point.
> * Items of the menu on the bottom should be arranged as the menu on the top.
> * Company information is Archway, not Archway Factory
> * Menu:
> 
> * Order of services in the menu, atlasian does not in menu service
>> recheck!
> 1. Services
> 
> * Microservice
> 
> * Explain content should be compared with ppt file:
> * Should review the layout of highlight content because it the same content with above but highlights.
>> re-check.
> * Missed content in p5 of ppt
>> will be fix.
> 
> * DevOps:
> 
> * Content not enough >> re-check?
>   
>   * 新しい開発スタイルの適用によるビジネス価値提供サイクルの劇的な短縮を実現します。
>   * DevOps 導入: List does not show all mean
>> do not understand
> * Atlassian
> 
> * Main color
> * Highlight section color
> * Content items
>> no change

**Comment by VienArchway** [comment]
remain: 

Services

- [ ]  Missed content in p5 of ppt

**Comment by ngochaarchway** [comment]
1. Top page
- Thiếu câu hỏi dẫn nhập. Vì nó cũng là 1 nội dung quan trọng
マイクロサービスの開発を、どのように導入・移行して良いかわからず、モノリシックなアプリケーションを保守し続けていませんか？
- Chưa hiểu nội dung lắm
2. Services
- Thứ tự trong menu ở home page
- DevOps導入サービス
 + DevOps サービスの取扱製品(一部) Đưa lên đầu tiên k phù hợp. Nó chỉ là nội dung bổ trợ thêm. Và nội dung cũng k đủ
 + Thể hiện content chưa rõ lắm: VD: -> Thời gian: Nhưng mà chưa nghĩ ra là thay đổi làm sao nên chắc là đợi xem bên kia feedback thế nào
 + Tại sao lại dùng format Title: detail mà k phải là Title -> Xuống dòng là detail content. Vì có những content tách thành nhiều ý, nếu viết kiểu xuống dòng tách ý ra sẽ rõ ràng hơn. Dấu ":" dùng ở đây k phù hợp lắm.
 + DevOps 導入
  * Thiếu dòng giới thiệu
  * Thiếu link アトラシアン製品 trong contett
 + 開発基礎トレーニング
  * Bố cục nội dung chưa phù hợp:
    - Các page khác bố trí chéo nhau. Vì sao ở page này có 2 mục nằm cùng phía với nhau.
 + テストトレーニング
  * Tại sao lại cần highlight nội dung thứ 2 lên. Cả 2 ý cùng để giải thích lý do cho việc cần làm automation test.
- R & D
+ Để vô menu thì có bị thiếu thông giới thiệu khác không. 
+ Sao có chỗ dùng tiếng anh, chỗ dùng tiếng Nhật
 + Software
  * Tại sao lại highlight phần giải thích ※１：
  * Tại sao lại tách ra ソフトウェアファクトリ 1 phần riêng.
